services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_RANDOM_ROOT_PASSWORD=false
